npmRegistries:
  //registry.npmjs.org/:
    npmAlwaysAuth: true
    npmAuthToken: '${NODE_AUTH_TOKEN:-}'

npmScopes:
  starlord25:
    npmAlwaysAuth: true
    npmAuthToken: '${NODE_AUTH_TOKEN:-}'
    npmRegistryServer: 'https://registry.npmjs.org/'


yarnPath: .yarn/releases/yarn-3.2.4.cjs
