name: Build
"on": pull_request
jobs:
  build_and_preview:
    if: "${{ github.event.pull_request.head.repo.full_name == github.repository }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: "22.x"
          cache: "yarn"
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache
        env:
          NODE_AUTH_TOKEN: ${{ secrets.YARN_TOKEN }}
      - name: Build
        run: yarn build-all
